setup: 'horizontal'
experimental_hutch: 1
local_data_path: 'path'
local_output_path: 'path'
beam_centre: null
detector_distance: 0.18
slitvertratio: 1.0
slithorratio: 1.0
alphacritical: 0.0
using_dps: False
dpsx_central_pixel: 0
dpsy_central_pixel: 0
dpsz_central_pixel: 0
output_file_size: 50
save_vtk: False
save_npy: False
volume_start: null
volume_stop: null
volume_step: null
load_from_dat: False
radialrange: null
radialstepval: 0.01
qmapbins: !!python/tuple [1200, 1200]
ivqbins: null
edfmaskfile: null
specific_pixels: null 
mask_regions: null
min_intensity: 0.
skipscans: []
skipimages: [[],[]]
process_outputs: []
map_per_image: False
savetiffs: False
savedats: False
frame_name: 'hkl'
coordinates: 'cartesian'
cylinder_axis: False 
DEBUG_LOG: 0 
spherical_bragg_vec: [0,0,0]